version: '2.1'

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=a
      - MYSQL_DATABASE=schoolattandence
      - MYSQL_USER=lucia
      - MYSQL_PASSWORD=a
  spring-boot-jpa-docker-webapp:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=lucia
      - DATABASE_PASSWORD=a
      - DATABASE_NAME=schoolattandence
      - DATABASE_PORT=3306




